// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: hello.proto at 7:1
package proto.hello;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Hello extends Message<Hello, Hello.Builder> {
  public static final ProtoAdapter<Hello> ADAPTER = new ProtoAdapter_Hello();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_NAME = "";

  public static final Integer DEFAULT_NUMBER = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String name;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer number;

  public Hello(String name, Integer number) {
    this(name, number, ByteString.EMPTY);
  }

  public Hello(String name, Integer number, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.name = name;
    this.number = number;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.name = name;
    builder.number = number;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Hello)) return false;
    Hello o = (Hello) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(name, o.name)
        && Internal.equals(number, o.number);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (number != null ? number.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (name != null) builder.append(", name=").append(name);
    if (number != null) builder.append(", number=").append(number);
    return builder.replace(0, 2, "Hello{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Hello, Builder> {
    public String name;

    public Integer number;

    public Builder() {
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder number(Integer number) {
      this.number = number;
      return this;
    }

    @Override
    public Hello build() {
      return new Hello(name, number, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Hello extends ProtoAdapter<Hello> {
    ProtoAdapter_Hello() {
      super(FieldEncoding.LENGTH_DELIMITED, Hello.class);
    }

    @Override
    public int encodedSize(Hello value) {
      return (value.name != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.name) : 0)
          + (value.number != null ? ProtoAdapter.INT32.encodedSizeWithTag(2, value.number) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Hello value) throws IOException {
      if (value.name != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name);
      if (value.number != null) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.number);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Hello decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.number(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Hello redact(Hello value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
